import {
  District,
  Contact,
  Campaign,
  CampaignDetail,
  EmailTemplate,
  DashboardStats,
  CampaignAnalytics,
  ActivityItem,
} from "@/types";

// ── States ───────────────────────────────────────────────────────────
export const US_STATES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",
  "HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
  "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
  "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
  "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY",
];

// ── Districts ────────────────────────────────────────────────────────
export const mockDistricts: District[] = [
  {
    id: "d1",
    name: "Houston Independent School District",
    state: "TX",
    city: "Houston",
    address: "4400 W 18th St, Houston, TX 77092",
    phone: "(713) 556-6000",
    website: "https://www.houstonisd.org",
    totalStudents: 196943,
    ellStudents: 62221,
    ellPercentage: 31.6,
    hasEslProgram: true,
    hasTitleI: true,
    titleIFunding: 85000000,
    titleIIIFunding: 12500000,
    superintendent: "Mike Miles",
    superintendentEmail: "mmiles@houstonisd.org",
    status: "active",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-03-10T14:30:00Z",
  },
  {
    id: "d2",
    name: "Los Angeles Unified School District",
    state: "CA",
    city: "Los Angeles",
    address: "333 S Beaudry Ave, Los Angeles, CA 90017",
    phone: "(213) 241-1000",
    website: "https://www.lausd.net",
    totalStudents: 422276,
    ellStudents: 118237,
    ellPercentage: 28.0,
    hasEslProgram: true,
    hasTitleI: true,
    titleIFunding: 142000000,
    titleIIIFunding: 18750000,
    superintendent: "Alberto Carvalho",
    superintendentEmail: "acarvalho@lausd.net",
    status: "active",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-03-12T09:15:00Z",
  },
  {
    id: "d3",
    name: "Chicago Public Schools",
    state: "IL",
    city: "Chicago",
    address: "42 W Madison St, Chicago, IL 60602",
    phone: "(773) 553-1000",
    website: "https://www.cps.edu",
    totalStudents: 321000,
    ellStudents: 57780,
    ellPercentage: 18.0,
    hasEslProgram: true,
    hasTitleI: true,
    titleIFunding: 118000000,
    titleIIIFunding: 9800000,
    superintendent: "Pedro Martinez",
    superintendentEmail: "pmartinez@cps.edu",
    status: "active",
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-03-08T11:45:00Z",
  },
  {
    id: "d4",
    name: "Miami-Dade County Public Schools",
    state: "FL",
    city: "Miami",
    address: "1450 NE 2nd Ave, Miami, FL 33132",
    phone: "(305) 995-1000",
    website: "https://www.dadeschools.net",
    totalStudents: 334261,
    ellStudents: 73538,
    ellPercentage: 22.0,
    hasEslProgram: true,
    hasTitleI: true,
    titleIFunding: 95000000,
    titleIIIFunding: 11200000,
    superintendent: "Jose Dotres",
    superintendentEmail: "jdotres@dadeschools.net",
    status: "active",
    createdAt: "2025-01-22T09:30:00Z",
    updatedAt: "2025-03-11T16:00:00Z",
  },
  {
    id: "d5",
    name: "Clark County School District",
    state: "NV",
    city: "Las Vegas",
    address: "5100 W Sahara Ave, Las Vegas, NV 89146",
    phone: "(702) 799-5011",
    website: "https://www.ccsd.net",
    totalStudents: 305030,
    ellStudents: 54905,
    ellPercentage: 18.0,
    hasEslProgram: true,
    hasTitleI: true,
    titleIFunding: 88000000,
    titleIIIFunding: 8900000,
    superintendent: "Jesus Jara",
    superintendentEmail: "jjara@ccsd.net",
    status: "active",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-03-10T10:00:00Z",
  },
  {
    id: "d6",
    name: "Fairfax County Public Schools",
    state: "VA",
    city: "Falls Church",
    address: "8115 Gatehouse Rd, Falls Church, VA 22042",
    phone: "(571) 423-1000",
    website: "https://www.fcps.edu",
    totalStudents: 180222,
    ellStudents: 45056,
    ellPercentage: 25.0,
    hasEslProgram: true,
    hasTitleI: true,
    titleIFunding: 42000000,
    titleIIIFunding: 7600000,
    superintendent: "Michelle Reid",
    superintendentEmail: "mreid@fcps.edu",
    status: "active",
    createdAt: "2025-02-05T11:00:00Z",
    updatedAt: "2025-03-09T14:20:00Z",
  },
  {
    id: "d7",
    name: "Denver Public Schools",
    state: "CO",
    city: "Denver",
    address: "1860 Lincoln St, Denver, CO 80203",
    phone: "(720) 423-3200",
    website: "https://www.dpsk12.org",
    totalStudents: 87000,
    ellStudents: 29580,
    ellPercentage: 34.0,
    hasEslProgram: true,
    hasTitleI: true,
    titleIFunding: 28000000,
    titleIIIFunding: 5200000,
    superintendent: "Alex Marrero",
    superintendentEmail: "amarrero@dpsk12.org",
    status: "active",
    createdAt: "2025-02-10T09:00:00Z",
    updatedAt: "2025-03-13T08:30:00Z",
  },
  {
    id: "d8",
    name: "Springfield Public Schools",
    state: "MO",
    city: "Springfield",
    address: "1359 E St Louis St, Springfield, MO 65802",
    phone: "(417) 523-0000",
    website: "https://www.sps.org",
    totalStudents: 24500,
    ellStudents: 2450,
    ellPercentage: 10.0,
    hasEslProgram: false,
    hasTitleI: true,
    titleIFunding: 8500000,
    titleIIIFunding: 450000,
    superintendent: "Grenita Lathan",
    superintendentEmail: "glathan@sps.org",
    status: "pending",
    createdAt: "2025-02-15T10:00:00Z",
    updatedAt: "2025-03-14T12:00:00Z",
  },
  {
    id: "d9",
    name: "Anchorage School District",
    state: "AK",
    city: "Anchorage",
    address: "5530 E Northern Lights Blvd, Anchorage, AK 99504",
    phone: "(907) 742-4000",
    website: "https://www.asdk12.org",
    totalStudents: 42000,
    ellStudents: 5460,
    ellPercentage: 13.0,
    hasEslProgram: true,
    hasTitleI: true,
    titleIFunding: 15000000,
    titleIIIFunding: 1800000,
    superintendent: "Jharrett Bryantt",
    superintendentEmail: "jbryantt@asdk12.org",
    status: "active",
    createdAt: "2025-02-18T08:00:00Z",
    updatedAt: "2025-03-12T10:45:00Z",
  },
  {
    id: "d10",
    name: "Boston Public Schools",
    state: "MA",
    city: "Boston",
    address: "2300 Washington St, Boston, MA 02119",
    phone: "(617) 635-9000",
    website: "https://www.bostonpublicschools.org",
    totalStudents: 49000,
    ellStudents: 15680,
    ellPercentage: 32.0,
    hasEslProgram: true,
    hasTitleI: true,
    titleIFunding: 22000000,
    titleIIIFunding: 4100000,
    superintendent: "Mary Skipper",
    superintendentEmail: "mskipper@bostonpublicschools.org",
    status: "active",
    createdAt: "2025-02-20T09:30:00Z",
    updatedAt: "2025-03-15T11:00:00Z",
  },
];

// ── Contacts ─────────────────────────────────────────────────────────
export const mockContacts: Contact[] = [
  {
    id: "c1",
    firstName: "Mike",
    lastName: "Miles",
    role: "Superintendent",
    districtId: "d1",
    districtName: "Houston Independent School District",
    state: "TX",
    email: "mmiles@houstonisd.org",
    emailStatus: "verified",
    phone: "(713) 556-6001",
    confidenceScore: 95,
    linkedinUrl: "https://linkedin.com/in/mikemiles",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-03-10T14:30:00Z",
  },
  {
    id: "c2",
    firstName: "Alberto",
    lastName: "Carvalho",
    role: "Superintendent",
    districtId: "d2",
    districtName: "Los Angeles Unified School District",
    state: "CA",
    email: "acarvalho@lausd.net",
    emailStatus: "verified",
    phone: "(213) 241-1001",
    confidenceScore: 98,
    linkedinUrl: "https://linkedin.com/in/albertocarvalho",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-03-12T09:15:00Z",
  },
  {
    id: "c3",
    firstName: "Pedro",
    lastName: "Martinez",
    role: "Superintendent",
    districtId: "d3",
    districtName: "Chicago Public Schools",
    state: "IL",
    email: "pmartinez@cps.edu",
    emailStatus: "verified",
    phone: "(773) 553-1001",
    confidenceScore: 92,
    linkedinUrl: "https://linkedin.com/in/pedromartinez",
    createdAt: "2025-01-20T08:00:00Z",
    updatedAt: "2025-03-08T11:45:00Z",
  },
  {
    id: "c4",
    firstName: "Sarah",
    lastName: "Nguyen",
    role: "Director of ELL",
    districtId: "d1",
    districtName: "Houston Independent School District",
    state: "TX",
    email: "snguyen@houstonisd.org",
    emailStatus: "verified",
    phone: "(713) 556-6200",
    confidenceScore: 88,
    linkedinUrl: "",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-03-10T15:00:00Z",
  },
  {
    id: "c5",
    firstName: "Jose",
    lastName: "Dotres",
    role: "Superintendent",
    districtId: "d4",
    districtName: "Miami-Dade County Public Schools",
    state: "FL",
    email: "jdotres@dadeschools.net",
    emailStatus: "unverified",
    phone: "(305) 995-1001",
    confidenceScore: 75,
    linkedinUrl: "https://linkedin.com/in/josedotres",
    createdAt: "2025-01-22T09:30:00Z",
    updatedAt: "2025-03-11T16:00:00Z",
  },
  {
    id: "c6",
    firstName: "Jesus",
    lastName: "Jara",
    role: "Superintendent",
    districtId: "d5",
    districtName: "Clark County School District",
    state: "NV",
    email: "jjara@ccsd.net",
    emailStatus: "verified",
    phone: "(702) 799-5012",
    confidenceScore: 90,
    linkedinUrl: "",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-03-10T10:00:00Z",
  },
  {
    id: "c7",
    firstName: "Michelle",
    lastName: "Reid",
    role: "Superintendent",
    districtId: "d6",
    districtName: "Fairfax County Public Schools",
    state: "VA",
    email: "mreid@fcps.edu",
    emailStatus: "verified",
    phone: "(571) 423-1001",
    confidenceScore: 93,
    linkedinUrl: "https://linkedin.com/in/michellereid",
    createdAt: "2025-02-05T11:00:00Z",
    updatedAt: "2025-03-09T14:20:00Z",
  },
  {
    id: "c8",
    firstName: "Linda",
    lastName: "Park",
    role: "Director of ELL",
    districtId: "d2",
    districtName: "Los Angeles Unified School District",
    state: "CA",
    email: "lpark@lausd.net",
    emailStatus: "catch_all",
    phone: "(213) 241-2000",
    confidenceScore: 65,
    linkedinUrl: "",
    createdAt: "2025-02-10T09:00:00Z",
    updatedAt: "2025-03-13T08:30:00Z",
  },
  {
    id: "c9",
    firstName: "Robert",
    lastName: "Chen",
    role: "Assistant Superintendent",
    districtId: "d3",
    districtName: "Chicago Public Schools",
    state: "IL",
    email: "rchen@cps.edu",
    emailStatus: "bounced",
    phone: "(773) 553-2000",
    confidenceScore: 40,
    linkedinUrl: "https://linkedin.com/in/robertchen",
    createdAt: "2025-02-12T10:00:00Z",
    updatedAt: "2025-03-14T12:00:00Z",
  },
  {
    id: "c10",
    firstName: "Maria",
    lastName: "Garcia",
    role: "Curriculum Director",
    districtId: "d4",
    districtName: "Miami-Dade County Public Schools",
    state: "FL",
    email: "mgarcia@dadeschools.net",
    emailStatus: "unknown",
    phone: "(305) 995-2000",
    confidenceScore: 55,
    linkedinUrl: "",
    createdAt: "2025-02-15T10:00:00Z",
    updatedAt: "2025-03-15T11:00:00Z",
  },
  {
    id: "c11",
    firstName: "Alex",
    lastName: "Marrero",
    role: "Superintendent",
    districtId: "d7",
    districtName: "Denver Public Schools",
    state: "CO",
    email: "amarrero@dpsk12.org",
    emailStatus: "verified",
    phone: "(720) 423-3201",
    confidenceScore: 91,
    linkedinUrl: "",
    createdAt: "2025-02-10T09:00:00Z",
    updatedAt: "2025-03-13T08:30:00Z",
  },
  {
    id: "c12",
    firstName: "Mary",
    lastName: "Skipper",
    role: "Superintendent",
    districtId: "d10",
    districtName: "Boston Public Schools",
    state: "MA",
    email: "mskipper@bostonpublicschools.org",
    emailStatus: "verified",
    phone: "(617) 635-9001",
    confidenceScore: 96,
    linkedinUrl: "https://linkedin.com/in/maryskipper",
    createdAt: "2025-02-20T09:30:00Z",
    updatedAt: "2025-03-15T11:00:00Z",
  },
];

// ── Campaigns ────────────────────────────────────────────────────────
export const mockCampaigns: Campaign[] = [
  {
    id: "camp1",
    name: "Spring 2025 - ELL Program Outreach",
    description: "Reaching out to superintendents in districts with high ELL populations about our language learning platform.",
    status: "active",
    enrolled: 45,
    sent: 120,
    opened: 78,
    clicked: 34,
    replied: 12,
    bounced: 3,
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-03-15T14:30:00Z",
  },
  {
    id: "camp2",
    name: "Title III Funding Recipients",
    description: "Targeting districts receiving Title III funding for ESL/bilingual education programs.",
    status: "active",
    enrolled: 32,
    sent: 64,
    opened: 38,
    clicked: 15,
    replied: 7,
    bounced: 1,
    createdAt: "2025-02-15T09:00:00Z",
    updatedAt: "2025-03-14T11:00:00Z",
  },
  {
    id: "camp3",
    name: "California Districts - Pilot Program",
    description: "Pilot outreach to large California school districts with established ESL programs.",
    status: "completed",
    enrolled: 18,
    sent: 54,
    opened: 41,
    clicked: 22,
    replied: 9,
    bounced: 0,
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-02-28T16:00:00Z",
  },
  {
    id: "camp4",
    name: "Q2 2025 - New Districts",
    description: "Outreach to newly identified districts with growing ELL populations.",
    status: "draft",
    enrolled: 0,
    sent: 0,
    opened: 0,
    clicked: 0,
    replied: 0,
    bounced: 0,
    createdAt: "2025-03-10T10:00:00Z",
    updatedAt: "2025-03-10T10:00:00Z",
  },
  {
    id: "camp5",
    name: "Re-engagement - No Reply",
    description: "Follow-up campaign for contacts who did not reply to previous outreach.",
    status: "paused",
    enrolled: 28,
    sent: 28,
    opened: 14,
    clicked: 6,
    replied: 2,
    bounced: 2,
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-03-12T09:00:00Z",
  },
];

export const mockCampaignDetail: CampaignDetail = {
  ...mockCampaigns[0],
  steps: [
    {
      id: "s1",
      order: 1,
      delayDays: 0,
      templateId: "t1",
      templateName: "Initial Outreach",
      subject: "Improving ELL outcomes at {{district.name}}",
    },
    {
      id: "s2",
      order: 2,
      delayDays: 3,
      templateId: "t2",
      templateName: "Follow-up #1",
      subject: "Re: ELL program support for {{district.name}}",
    },
    {
      id: "s3",
      order: 3,
      delayDays: 5,
      templateId: "t3",
      templateName: "Value Add",
      subject: "Case study: How districts like {{district.name}} improved ELL scores",
    },
    {
      id: "s4",
      order: 4,
      delayDays: 7,
      templateId: "t4",
      templateName: "Final Follow-up",
      subject: "Last note about ELL support for {{district.name}}",
    },
  ],
  enrollments: [
    {
      id: "e1",
      contactId: "c1",
      contactName: "Mike Miles",
      contactEmail: "mmiles@houstonisd.org",
      districtName: "Houston ISD",
      currentStep: 3,
      status: "active",
      enrolledAt: "2025-02-01T10:00:00Z",
      lastActivityAt: "2025-03-14T09:00:00Z",
    },
    {
      id: "e2",
      contactId: "c2",
      contactName: "Alberto Carvalho",
      contactEmail: "acarvalho@lausd.net",
      districtName: "Los Angeles USD",
      currentStep: 4,
      status: "completed",
      enrolledAt: "2025-02-01T10:00:00Z",
      lastActivityAt: "2025-03-10T14:00:00Z",
    },
    {
      id: "e3",
      contactId: "c3",
      contactName: "Pedro Martinez",
      contactEmail: "pmartinez@cps.edu",
      districtName: "Chicago Public Schools",
      currentStep: 2,
      status: "replied",
      enrolledAt: "2025-02-05T10:00:00Z",
      lastActivityAt: "2025-03-12T11:00:00Z",
    },
    {
      id: "e4",
      contactId: "c5",
      contactName: "Jose Dotres",
      contactEmail: "jdotres@dadeschools.net",
      districtName: "Miami-Dade County PS",
      currentStep: 1,
      status: "bounced",
      enrolledAt: "2025-02-10T10:00:00Z",
      lastActivityAt: "2025-02-10T10:30:00Z",
    },
    {
      id: "e5",
      contactId: "c6",
      contactName: "Jesus Jara",
      contactEmail: "jjara@ccsd.net",
      districtName: "Clark County SD",
      currentStep: 3,
      status: "active",
      enrolledAt: "2025-02-01T10:00:00Z",
      lastActivityAt: "2025-03-13T08:00:00Z",
    },
  ],
};

// ── Templates ────────────────────────────────────────────────────────
export const mockTemplates: EmailTemplate[] = [
  {
    id: "t1",
    name: "Initial Outreach",
    subject: "Improving ELL outcomes at {{district.name}}",
    body: `Dear {{contact.first_name}},

I hope this message finds you well. I'm reaching out because {{district.name}} serves {{district.ell_students}} English Language Learners, and I believe our platform could make a meaningful difference in your ELL program outcomes.

Our solution has helped districts similar to yours:
- Increase ELL assessment scores by an average of 23%
- Reduce teacher preparation time for differentiated ELL instruction by 40%
- Improve parent engagement among ELL families by 35%

Would you have 15 minutes this week for a brief conversation about how we might support your ELL initiatives?

Best regards,
{{sender.name}}
{{sender.title}}`,
    variables: [
      "contact.first_name",
      "district.name",
      "district.ell_students",
      "sender.name",
      "sender.title",
    ],
    createdAt: "2025-01-20T10:00:00Z",
    updatedAt: "2025-02-15T14:00:00Z",
  },
  {
    id: "t2",
    name: "Follow-up #1",
    subject: "Re: ELL program support for {{district.name}}",
    body: `Hi {{contact.first_name}},

I wanted to follow up on my previous email about supporting ELL outcomes at {{district.name}}.

I understand you're busy managing a district of {{district.total_students}} students, so I'll keep this brief: we recently published a case study showing how a district with a similar ELL population improved their ACCESS scores by 28% in one academic year.

I'd love to share this with you. Would a 10-minute call work this week?

Best,
{{sender.name}}`,
    variables: [
      "contact.first_name",
      "district.name",
      "district.total_students",
      "sender.name",
    ],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-02-15T14:30:00Z",
  },
  {
    id: "t3",
    name: "Value Add",
    subject: "Case study: How districts like {{district.name}} improved ELL scores",
    body: `{{contact.first_name}},

I thought you might find this relevant - we just helped a {{district.state}} district with {{district.ell_students}} ELL students achieve:

- 31% improvement in English proficiency assessments
- 45% increase in ELL student graduation rates
- Significant reduction in long-term ELL classification

These results were achieved within the first academic year of implementation.

I've attached the full case study. Happy to discuss how we could tailor a similar approach for {{district.name}}.

{{sender.name}}
{{sender.title}}
{{sender.company}}`,
    variables: [
      "contact.first_name",
      "district.name",
      "district.state",
      "district.ell_students",
      "sender.name",
      "sender.title",
      "sender.company",
    ],
    createdAt: "2025-01-25T10:00:00Z",
    updatedAt: "2025-02-16T09:00:00Z",
  },
  {
    id: "t4",
    name: "Final Follow-up",
    subject: "Last note about ELL support for {{district.name}}",
    body: `Hi {{contact.first_name}},

I don't want to take up more of your time, so this will be my last note.

If improving ELL outcomes at {{district.name}} is a priority for the upcoming school year, I'd welcome the chance to show you what we've built. Our platform is specifically designed for districts with significant ELL populations.

If now isn't the right time, no worries at all. Feel free to reach out whenever it makes sense.

Wishing you and your team a great rest of the school year.

{{sender.name}}
{{sender.company}}`,
    variables: [
      "contact.first_name",
      "district.name",
      "sender.name",
      "sender.company",
    ],
    createdAt: "2025-01-28T10:00:00Z",
    updatedAt: "2025-02-16T09:30:00Z",
  },
];

// ── Dashboard Stats ──────────────────────────────────────────────────
export const mockDashboardStats: DashboardStats = {
  totalDistricts: 247,
  districtsWithEsl: 189,
  districtsWithTitleI: 221,
  totalContacts: 412,
  verifiedContacts: 298,
  unverifiedContacts: 114,
  activeCampaigns: 2,
  emailsSentToday: 34,
  emailsSentThisWeek: 187,
};

// ── Campaign Analytics ───────────────────────────────────────────────
export const mockCampaignAnalytics: CampaignAnalytics = {
  campaignId: "camp1",
  openRate: 65.0,
  clickRate: 28.3,
  replyRate: 10.0,
  bounceRate: 2.5,
  unsubscribeRate: 0.8,
  dailyStats: [
    { date: "2025-03-09", sent: 12, opened: 8, clicked: 3, replied: 1 },
    { date: "2025-03-10", sent: 15, opened: 10, clicked: 5, replied: 2 },
    { date: "2025-03-11", sent: 10, opened: 7, clicked: 3, replied: 1 },
    { date: "2025-03-12", sent: 18, opened: 12, clicked: 6, replied: 3 },
    { date: "2025-03-13", sent: 14, opened: 9, clicked: 4, replied: 1 },
    { date: "2025-03-14", sent: 11, opened: 8, clicked: 4, replied: 2 },
    { date: "2025-03-15", sent: 8, opened: 5, clicked: 2, replied: 1 },
  ],
};

// ── Activity Feed ────────────────────────────────────────────────────
export const mockActivityFeed: ActivityItem[] = [
  {
    id: "a1",
    type: "reply_received",
    description: "Pedro Martinez (Chicago PS) replied to campaign \"Spring 2025 - ELL Program Outreach\"",
    timestamp: "2025-03-15T14:23:00Z",
  },
  {
    id: "a2",
    type: "email_opened",
    description: "Michelle Reid (Fairfax County PS) opened \"Improving ELL outcomes at Fairfax County Public Schools\"",
    timestamp: "2025-03-15T13:45:00Z",
  },
  {
    id: "a3",
    type: "email_sent",
    description: "Sent follow-up #2 to Jesus Jara (Clark County SD)",
    timestamp: "2025-03-15T12:00:00Z",
  },
  {
    id: "a4",
    type: "contact_added",
    description: "Added 5 new contacts from Denver Public Schools",
    timestamp: "2025-03-15T10:30:00Z",
  },
  {
    id: "a5",
    type: "bounce",
    description: "Email bounced for Robert Chen (rchen@cps.edu) - invalid address",
    timestamp: "2025-03-15T09:15:00Z",
  },
  {
    id: "a6",
    type: "campaign_started",
    description: "Campaign \"Title III Funding Recipients\" started with 32 enrollments",
    timestamp: "2025-03-14T16:00:00Z",
  },
  {
    id: "a7",
    type: "email_opened",
    description: "Alex Marrero (Denver PS) opened \"Case study: How districts like Denver Public Schools improved ELL scores\"",
    timestamp: "2025-03-14T14:10:00Z",
  },
  {
    id: "a8",
    type: "reply_received",
    description: "Mary Skipper (Boston PS) replied to campaign \"Title III Funding Recipients\"",
    timestamp: "2025-03-14T11:30:00Z",
  },
];
